"""update_gitlab_models_optional_fields

Revision ID: 7cb6e6a0a097
Revises: 8cb68868fb72
Create Date: 2026-01-24 17:49:30.254195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb6e6a0a097'
down_revision: Union[str, Sequence[str], None] = '8cb68868fb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitlabusergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gitlabusergroup_owner_id'))

    op.drop_table('gitlabusergroup')
    with op.batch_alter_table('gitlabusergroupmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gitlabusergroupmember_group_id'))

    op.drop_table('gitlabusergroupmember')
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_concurrent_chunks', sa.Integer(), nullable=False))
        batch_op.alter_column('enable_ai_debug_dump',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('projectwatchlist', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('timersession', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('timersession', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('projectwatchlist', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.alter_column('enable_ai_debug_dump',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('max_concurrent_chunks')

    op.create_table('gitlabusergroupmember',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['gitlabusergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gitlabusergroupmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gitlabusergroupmember_group_id'), ['group_id'], unique=False)

    op.create_table('gitlabusergroup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gitlabusergroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gitlabusergroup_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###
