"""Add AI Work Summary models

Revision ID: 49dd59a46562
Revises: d30264d0e335
Create Date: 2026-01-19 23:56:24.868569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dd59a46562'
down_revision: Union[str, Sequence[str], None] = 'd30264d0e335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prdconversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prdconversation_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prdconversation_project_id'))

    op.drop_table('prdconversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prdconversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(), nullable=False),
    sa.Column('messages', sa.VARCHAR(), nullable=False),
    sa.Column('generated_tasks', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prdconversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prdconversation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prdconversation_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###
