"""Add relations column

Revision ID: 03acf7f9379f
Revises: 7cb6e6a0a097
Create Date: 2026-01-27 22:37:00.850005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03acf7f9379f'
down_revision: Union[str, Sequence[str], None] = '7cb6e6a0a097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackedtask', sa.Column('relations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackedtask', 'relations')
    # ### end Alembic commands ###
