"""add_prd_planning_models

Revision ID: ceece7c61cb1
Revises: 36bbd9340512
Create Date: 2026-01-18 18:13:59.075642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ceece7c61cb1'
down_revision: Union[str, Sequence[str], None] = '36bbd9340512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prddocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_history', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prddocument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prddocument_owner_id'), ['owner_id'], unique=False)

    op.create_table('planningproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prd_document_id', sa.Integer(), nullable=True),
    sa.Column('redmine_project_id', sa.Integer(), nullable=True),
    sa.Column('redmine_project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sync_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prd_document_id'], ['prddocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planningproject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planningproject_owner_id'), ['owner_id'], unique=False)

    op.create_table('planningtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planning_project_id', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('redmine_issue_id', sa.Integer(), nullable=True),
    sa.Column('is_from_redmine', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planning_project_id'], ['planningproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planningtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planningtask_planning_project_id'), ['planning_project_id'], unique=False)

    op.create_table('taskdependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=False),
    sa.Column('target_task_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_task_id'], ['planningtask.id'], ),
    sa.ForeignKeyConstraint(['target_task_id'], ['planningtask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taskdependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taskdependency_source_task_id'), ['source_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_taskdependency_target_task_id'), ['target_task_id'], unique=False)

    with op.batch_alter_table('prdconversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prdconversation_owner_id'))
        batch_op.drop_index(batch_op.f('ix_prdconversation_project_id'))

    op.drop_table('prdconversation')
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.alter_column('ldap_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('redmine_default_activity_id')

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('spent_hours',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_foreign_key('fk_trackedtask_owner_id', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('usersettings', schema=None) as batch_op:
        batch_op.alter_column('task_warning_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('task_severe_warning_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersettings', schema=None) as batch_op:
        batch_op.alter_column('task_severe_warning_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('task_warning_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trackedtask_owner_id', type_='foreignkey')
        batch_op.alter_column('spent_hours',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redmine_default_activity_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('ldap_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('prdconversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(), nullable=False),
    sa.Column('messages', sa.VARCHAR(), nullable=False),
    sa.Column('generated_tasks', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prdconversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prdconversation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prdconversation_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('taskdependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taskdependency_target_task_id'))
        batch_op.drop_index(batch_op.f('ix_taskdependency_source_task_id'))

    op.drop_table('taskdependency')
    with op.batch_alter_table('planningtask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planningtask_planning_project_id'))

    op.drop_table('planningtask')
    with op.batch_alter_table('planningproject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planningproject_owner_id'))

    op.drop_table('planningproject')
    with op.batch_alter_table('prddocument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prddocument_owner_id'))

    op.drop_table('prddocument')
    # ### end Alembic commands ###
