"""add_parent_and_author_to_tracked_task

Revision ID: 8deb7d278eba
Revises: 372f4a9c1c64
Create Date: 2026-01-24 01:10:42.180783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8deb7d278eba'
down_revision: Union[str, Sequence[str], None] = '372f4a9c1c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.drop_column('author_name')
        batch_op.drop_column('author_id')
        batch_op.drop_column('parent_subject')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
