"""Add meta fields to PlanningTask

Revision ID: d30264d0e335
Revises: ceece7c61cb1
Create Date: 2026-01-18 19:19:14.942806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd30264d0e335'
down_revision: Union[str, Sequence[str], None] = 'ceece7c61cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_appsettings')
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.alter_column('ldap_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('redmine_default_activity_id')

    with op.batch_alter_table('planningtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('redmine_updated_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('spent_hours',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_foreign_key('fk_trackedtask_user_id', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('usersettings', schema=None) as batch_op:
        batch_op.alter_column('task_warning_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
        batch_op.alter_column('task_severe_warning_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersettings', schema=None) as batch_op:
        batch_op.alter_column('task_severe_warning_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
        batch_op.alter_column('task_warning_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('spent_hours',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('planningtask', schema=None) as batch_op:
        batch_op.drop_column('redmine_updated_on')
        batch_op.drop_column('status_name')
        batch_op.drop_column('status_id')
        batch_op.drop_column('assigned_to_name')
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redmine_default_activity_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('ldap_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('_alembic_tmp_appsettings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('ldap_enabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
