"""add max_concurrent_chunks

Revision ID: 372f4a9c1c64
Revises: 231381fe8d29
Create Date: 2026-01-23 14:58:30.467229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372f4a9c1c64'
down_revision: Union[str, Sequence[str], None] = '231381fe8d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_concurrent_chunks', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        batch_op.drop_column('max_concurrent_chunks')

    # ### end Alembic commands ###
