"""add_gitlab_granular_monitoring_fields

Revision ID: 8cb68868fb72
Revises: 8deb7d278eba
Create Date: 2026-01-24 11:23:09.467027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cb68868fb72'
down_revision: Union[str, Sequence[str], None] = '8deb7d278eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aiworksummaryreport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gitlab_metrics', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    with op.batch_alter_table('aiworksummarysettings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_gitlab_project_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='[]'))

    with op.batch_alter_table('gitlabinstance', schema=None) as batch_op:
        batch_op.alter_column('target_users_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('target_projects_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('gitlabwatchlist', schema=None) as batch_op:
        batch_op.alter_column('is_included',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gitlabwatchlist', schema=None) as batch_op:
        batch_op.alter_column('is_included',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('gitlabinstance', schema=None) as batch_op:
        batch_op.alter_column('target_projects_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('target_users_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('aiworksummarysettings', schema=None) as batch_op:
        batch_op.drop_column('target_gitlab_project_ids')

    with op.batch_alter_table('aiworksummaryreport', schema=None) as batch_op:
        batch_op.drop_column('gitlab_metrics')

    # ### end Alembic commands ###
