"""Add owner_id to timersession and projectwatchlist and sync other models

Revision ID: 03fcfc6b044b
Revises: 5589caa04c6d
Create Date: 2026-01-17 20:46:28.496699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fcfc6b044b'
down_revision: Union[str, Sequence[str], None] = '5589caa04c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually create tables if they don't exist
    # Using 'IF NOT EXISTS' equivalent logic for SQLite
    bind = op.get_bind()
    
    # Create tables
    op.execute("CREATE TABLE IF NOT EXISTS ldapsettings (id INTEGER NOT NULL, server_url VARCHAR NOT NULL, base_dn VARCHAR NOT NULL, user_dn_template VARCHAR NOT NULL, bind_dn VARCHAR, bind_password VARCHAR, is_active BOOLEAN NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (id))")
    op.execute("CREATE TABLE IF NOT EXISTS user (id INTEGER NOT NULL, username VARCHAR NOT NULL, hashed_password VARCHAR, full_name VARCHAR, email VARCHAR, is_admin BOOLEAN NOT NULL, auth_source VARCHAR NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id))")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_username ON user (username)")
    op.execute("CREATE TABLE IF NOT EXISTS usersettings (id INTEGER NOT NULL, user_id INTEGER NOT NULL, redmine_url VARCHAR, api_key VARCHAR, redmine_default_activity_id INTEGER, openai_url VARCHAR, openai_key VARCHAR, openai_model VARCHAR, updated_at DATETIME NOT NULL, PRIMARY KEY (id), FOREIGN KEY(user_id) REFERENCES user (id), UNIQUE (user_id))")

    with op.batch_alter_table('appsettings', schema=None) as batch_op:
        # Check if columns exist before adding/dropping
        columns = [c['name'] for c in sa.inspect(bind).get_columns('appsettings')]
        if 'ldap_enabled' not in columns:
            batch_op.add_column(sa.Column('ldap_enabled', sa.Boolean(), nullable=False, server_default='0'))
        if 'redmine_url' in columns: batch_op.drop_column('redmine_url')
        if 'api_key' in columns: batch_op.drop_column('api_key')
        if 'openai_model' in columns: batch_op.drop_column('openai_model')
        if 'openai_key' in columns: batch_op.drop_column('openai_key')
        if 'openai_url' in columns: batch_op.drop_column('openai_url')

    with op.batch_alter_table('projectwatchlist', schema=None) as batch_op:
        columns = [c['name'] for c in sa.inspect(bind).get_columns('projectwatchlist')]
        if 'owner_id' not in columns:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
            batch_op.create_index(op.f('ix_projectwatchlist_owner_id'), ['owner_id'], unique=False)
            batch_op.create_foreign_key('fk_projectwatchlist_owner', 'user', ['owner_id'], ['id'])
        # Change unique index to non-unique
        # Indices in SQLite need to be dropped and recreated if they change
        try:
            batch_op.drop_index('ix_projectwatchlist_redmine_project_id')
        except:
            pass
        batch_op.create_index(op.f('ix_projectwatchlist_redmine_project_id'), ['redmine_project_id'], unique=False)

    with op.batch_alter_table('timersession', schema=None) as batch_op:
        columns = [c['name'] for c in sa.inspect(bind).get_columns('timersession')]
        if 'owner_id' not in columns:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
            batch_op.create_index(op.f('ix_timersession_owner_id'), ['owner_id'], unique=False)
            batch_op.create_foreign_key('fk_timersession_owner', 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('trackedtask', schema=None) as batch_op:
        columns = [c['name'] for c in sa.inspect(bind).get_columns('trackedtask')]
        if 'owner_id' not in columns:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
            batch_op.create_index(op.f('ix_trackedtask_owner_id'), ['owner_id'], unique=False)
            batch_op.create_foreign_key('fk_trackedtask_owner', 'user', ['owner_id'], ['id'])
        try:
            batch_op.drop_index('ix_trackedtask_redmine_issue_id')
        except:
            pass
        batch_op.create_index(op.f('ix_trackedtask_redmine_issue_id'), ['redmine_issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackedtask', type_='foreignkey')
    op.drop_index(op.f('ix_trackedtask_owner_id'), table_name='trackedtask')
    op.drop_index(op.f('ix_trackedtask_redmine_issue_id'), table_name='trackedtask')
    op.create_index(op.f('ix_trackedtask_redmine_issue_id'), 'trackedtask', ['redmine_issue_id'], unique=1)
    op.drop_column('trackedtask', 'owner_id')
    op.drop_constraint(None, 'timersession', type_='foreignkey')
    op.drop_index(op.f('ix_timersession_owner_id'), table_name='timersession')
    op.drop_column('timersession', 'owner_id')
    op.drop_constraint(None, 'projectwatchlist', type_='foreignkey')
    op.drop_index(op.f('ix_projectwatchlist_owner_id'), table_name='projectwatchlist')
    op.drop_index(op.f('ix_projectwatchlist_redmine_project_id'), table_name='projectwatchlist')
    op.create_index(op.f('ix_projectwatchlist_redmine_project_id'), 'projectwatchlist', ['redmine_project_id'], unique=1)
    op.drop_column('projectwatchlist', 'owner_id')
    op.add_column('appsettings', sa.Column('openai_url', sa.VARCHAR(), nullable=True))
    op.add_column('appsettings', sa.Column('openai_key', sa.VARCHAR(), nullable=True))
    op.add_column('appsettings', sa.Column('openai_model', sa.VARCHAR(), nullable=True))
    op.add_column('appsettings', sa.Column('api_key', sa.VARCHAR(), nullable=True))
    op.add_column('appsettings', sa.Column('redmine_url', sa.VARCHAR(), nullable=True))
    op.drop_column('appsettings', 'ldap_enabled')
    op.drop_table('usersettings')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('ldapsettings')
    # ### end Alembic commands ###
