"""add_project_watchlist

Revision ID: 7870c138bddf
Revises: 
Create Date: 2026-01-17 15:06:43.019891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7870c138bddf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redmine_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectwatchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redmine_project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projectwatchlist_redmine_project_id'), 'projectwatchlist', ['redmine_project_id'], unique=True)
    op.create_table('timerlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redmine_issue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackedtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redmine_issue_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackedtask_redmine_issue_id'), 'trackedtask', ['redmine_issue_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackedtask_redmine_issue_id'), table_name='trackedtask')
    op.drop_table('trackedtask')
    op.drop_table('timerlog')
    op.drop_index(op.f('ix_projectwatchlist_redmine_project_id'), table_name='projectwatchlist')
    op.drop_table('projectwatchlist')
    op.drop_table('appsettings')
    # ### end Alembic commands ###
